### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by IzzySoft** [uintdev/qrserv#28]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I unfortunately was not even able to build the APK:

```
...

Downloading linux-x64 tools...                                   1,922ms
Downloading linux-x64/font-subset tools...                         294ms
Resolving dependencies...
The current Dart SDK version is 3.7.2.

Because qrserv requires SDK version >=3.8.0-265.0.dev <4.0.0, version solving failed.
Failed to update packages.
```

I've used the latest stable Flutter (currently 3.29.3) with the following recipe:

```yaml
build:
  - sed -r '/signingConfigs.getByName/d' -i android/app/build.gradle.kts
  - sed -r '/create\("release"\) \{/,/}/d' -i android/app/build.gradle.kts
  - FLUTTER_VERSION="3.29.3"
  - git clone -b $FLUTTER_VERSION https://github.com/flutter/flutter
  - export PUB_CACHE=$(pwd)/.pub-cache
  - flutter/bin/flutter config --no-analytics
  - flutter/bin/flutter pub get
  - flutter/bin/flutter build apk --release --target-platform android-arm
```

(the first two lines are just to remove the signing config, as we need an unsigned APK here). Did I miss a step? How can I see what Flutter version you are using? Maybe you could add flutter as git submodule, or add the version used to your `pubspec.yaml`:

```yaml
environment:
    sdk: '>= 3.8.0-265.0.dev <4.0.0'
    flutter: ^3.29.3
```

And while I'm here: could you let us know what path you build in, as Flutter loves to embed the build path in its native libs? That would save us a few test-runs to find it via e.g. Diffoscope 😉 

We'd appreciate if you could help making your build reproducible. We've also prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/RB-Hints-for-Developers) for that.

Looking forward to your reply!

**Comment by uintdev** [comment]
Hi,

This is currently on the main channel. I had created a new commit that adds the Flutter version and updated the Dart SDK version to line up with it (the versions used on the v2.7.0 release build).
```yaml
environment:
    sdk: '>= 3.9.0-96.0.dev <4.0.0'
    flutter: ^3.32.0-1.0.pre.412
```

I could try moving it to the stable channel, if that would ultimately help (really should be using that channel anyway).

Build path: "C:\Users\node\Projects\Projects\qrserv" (no typo here -- could've been better named)

**Comment by IzzySoft** [comment]
> Build path: "C:\Users\node\Projects\Projects\qrserv"

Oh… OK, then we have to give up. We cannot match Windows paths on Linux, unfortunately. So while we _might_ [get the build-id removed with cmake](https://github.com/AkaneTan/Gramophone/issues/424#issuecomment-2708373007) (which is used here), the path would remain in the way. AFAIR there was a way to use relative paths, which might solve the problem with the leading `C:`, I could not find my notes on this – and I don't know if it would work with Flutter.

@linsui you came up with this approach on a different project, can you tell?

An alternative would be to use Github action (or any other CI)s to build. Those would have the added benefit of guaranteeing a clean tree on each build 😉

**Comment by linsui** [comment]
I don't know how to remove the absolute path for flutter. I don't know how to pass a CFLAG to dart anyway. Not sure if it accepts something like that.

**Comment by IzzySoft** [comment]
Thanks @linsui! I guess flags could be passed from the [ndk section in `build.gradle`](https://github.com/uintdev/qrserv/blob/main/android/app/build.gradle.kts#L36), or from a corresponding  `cmake` section parallel to that. But I've lost the notes on this you made on another app, so I wouldn't even know how to try it. Dart seems just to prepare things, the native libs seem to be generated by `cmake` after it called `gradlew` (going by what I remember from the build logs) – though I'm not 100% sure, as the build logs from some Flutter apps do not mention cmake at all.

**Comment by linsui** [comment]
All tricks I know are documented in https://f-droid.org/docs/Reproducible_Builds/. For cmake, you can use `add_compile_options("-ffile-prefix-map=${CMAKE_CURRENT_SOURCE_DIR}=.")`. Some pub packages use cmake to build native libs but dart itself also has embeded path. I don't know how to fix the absolute path generated by dart itself.

**Comment by IzzySoft** [comment]
Thanks again, @linsui – I'll try to remember looking up that page before pinging you next time 🙈 

@uintdev that `add_compile_options` would need to go to `CMakeLists.txt`, which you don't have (at least I didn't see it). The alternative would be adding it to `build.gradle`:

```gradle
android {
   externalNativeBuild {
      cmake {
          cFlags "-ffile-prefix-map=${rootDir}=."
          cppFlags "-ffile-prefix-map=${rootDir}=."
       }
   }
}
```

If you want to give it a try, that is. If it's really Dart embedding the paths, we have no chance (apart from switching to e.g. CI builds via Github actions), we've tried that in the past but never succeeded.

**Comment by uintdev** [comment]
After adding the cmake flags into the `build.gradle.kts` file...
```kotlin
android {
    defaultConfig {
        externalNativeBuild {
            cmake {
                arguments += listOf(
                    "-DCMAKE_C_FLAGS=-ffile-prefix-map=${rootDir}=.",
                    "-DCMAKE_CXX_FLAGS=-ffile-prefix-map=${rootDir}=."
                )
            }
        }
    }
}
```
It did not appear to do anything. Tried various other options (even those brought up in issues regarding this). Nothing. Full path would still be around under `libapp.so`.
I tried Linux ARM64 -- even with Rosetta 2 (which helped get it much further) as to at least change it to a path that could be worked with, but Android Studio and some of the tooling (in this case, a filesystem watcher) prevents Android builds from succeeding for one reason or another. Officially, Android Studio isn't supported on Linux machines using ARM-based CPUs yet anyway.

I was thinking of maybe just building it on the Steam Deck as that is Linux AMD64.. assuming having an immutable system won't be an issue in this case. 🤔

**Comment by IzzySoft** [comment]
Steam Deck should work (I know someone using that for "coding while traveling"). If you want a quick setup for a build system there, you're welcome to use ours. Thanks to [rbuilder_setup](https://codeberg.org/IzzyOnDroid/rbuilder_setup) it takes less than 5 minutes to set it up, and I could give you the full build recipe I've used to get started with it. That would kinda work like a CI then, using Podman and ephemeral containers (to counter your immutable system 😜), thus guaranteeing a clean build on each run. The setup scripts support Debian & derivatives, RPM, and also Arch and derivatives, and thus cover most of the Linux world.

**Comment by linsui** [comment]
See https://github.com/flutter/flutter/issues/140558, even if you build the app in a windows-like path, there are other problems.

**Comment by IzzySoft** [comment]
Thanks once more! I've left a comment there to move it up again in the list (the last one was from LK more than a year ago). Maybe having a second party with a different build system chiming in helps raising the priority; idk, but worth a try.

**Comment by uintdev** [comment]
I see that the Steam OS (maybe as of 3.5) includes `podman`, which is nice. I had got Podman Desktop installed for the sake of simpler management. Of course, CLI is always an option.
Any suggestions as to how I should have the container set up? I'm not certain as to what details I'd need in the container configuration to ensure it plays well with rbuilder. In terms of the image, I'm looking at one from 'docker.io/library/ubuntu:24.04'.

**Comment by IzzySoft** [comment]
Oh, podman would be perfect. Maybe you want to try what we use? [rbuilder_setup](https://codeberg.org/IzzyOnDroid/rbuilder_setup) makes the setup a breeze, done in less than 5 minutes. I could offer you the recipe I tried to start with then, it has the image definition and all.

**Comment by uintdev** [comment]
Yeah, that would be great.

**Comment by IzzySoft** [comment]
This was the last recipe I've used. You'll probably need at least to adjust the Flutter version (ideally, you'd include Flutter as git submodule instead, and then skip the clone):

```yaml
---
repository: https://github.com/uintdev/qrserv.git
updates: releases
versions:
  - tag: v2.7.0
    apks:
      - apk_pattern: qrserv-.*-armeabi-v7a\.apk
        apk_url: https://github.com/uintdev/qrserv/releases/download/v2.7.0/qrserv-v2_7_0-armeabi-v7a.apk
        build:
          - sed -r '/signingConfigs.getByName/d' -i android/app/build.gradle.kts
          - sed -r '/create\("release"\) \{/,/}/d' -i android/app/build.gradle.kts
          - FLUTTER_VERSION="3.29.3"
          - git clone -b $FLUTTER_VERSION https://github.com/flutter/flutter
          - export PUB_CACHE=$(pwd)/.pub-cache
          - flutter/bin/flutter config --no-analytics
          - flutter/bin/flutter pub get
          - flutter/bin/flutter build apk --release --target-platform android-arm
          - find . -name '*.apk'
          - mv build/app/outputs/flutter-apk/app-release.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /build
        build_repo_dir: /build/repo
        build_timeout:
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages:
            - curl
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: false
```

The `find` in there is just for debug. Sometimes the resulting APKs have quite specific names 😉

**Comment by uintdev** [comment]
Got a lot of things configured on the Steam Deck for that immutable-by-default sort of environment.
I got a container running and went through the setup -- went smoothly. What would I need to use in order to take in the YAML config file?

**Comment by IzzySoft** [comment]
Just put the above into the `recipes/` directory as `dev.uint.qrserv.yml`. Then run `rblog build dev.uint.qrserv:v2.7.0::none local` (the `none` says to "compare the APK against no other", i.e. just build; between the `::` you can optionally specify a commit to build from if you don't want to build from the specified tag but just use the recipe from there). It things go well, you should end up with an APK file in `apks/`.

**Comment by uintdev** [comment]
Was able to get `libapp.so` to match up.

Recipe used:
```yaml
---
repository: https://github.com/uintdev/qrserv.git
updates: releases
versions:
  - tag: v2.7.2
    apks:
      - apk_pattern: qrserv-.*-armeabi-v7a\.apk
        apk_url: https://github.com/uintdev/qrserv/releases/download/v2.7.2/qrserv-v2_7_2-armeabi-v7a.apk
        build:
          - sed -r '/signingConfigs.getByName/d' -i android/app/build.gradle.kts
          - sed -r '/create\("release"\) \{/,/^        \}/d' -i android/app/build.gradle.kts
          - git config --global http.version HTTP/1.1
          - export PUB_CACHE=$(pwd)/.pub-cache
          - flutter/bin/flutter config --no-analytics
          - flutter/bin/flutter pub get
          - flutter/bin/flutter build apk --release --target-platform android-arm
          - find . -name '*.apk'
          - mv build/app/outputs/flutter-apk/app-release.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /home/deck
        build_repo_dir: /home/deck/Development/src/qrserv
        build_timeout:
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages:
            - curl
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: false

```

**Comment by IzzySoft** [comment]
> it failed to copy over the `squid.conf` file due to ` conf.d`

Thanks for the pointer! Updated the script accordingly. Seemingly the same issue with RPM, as there the scripts took care for this. Adjusted it for Arch (and DEB).

> I did notice that the instructions to automate sourcing of the environment mentions 'bashrc' when it should be '.bashrc'. Not hard to figure out that it's referring to that dot file, but just a small detail.

Where is that? I couldn't find it in the Readme.

>  `sed` commands trying to remove lines from the signingConfigs block.

Good catch! And the same fix which I had to apply to some other recipes in the past. Best of course if that `sed` [wouldn't be needed in the first place](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/RB-Hints-for-Developers#signing-config) 😉

> Was able to get `libapp.so` to match up.

🥳 Yeah, the embedded build path, or the build-id being calculated based on it… And now, to get it RB, let's also include `--split-per-abi` with the `flutter build` – as otherwise we get a different `versionCode`:

```diff
     XML ELEM START [lineno=2, name='manifest', #attributes=7]
-      ATTR: http://schemas.android.com/apk/res/android:versionCode=1052
+      ATTR: http://schemas.android.com/apk/res/android:versionCode=52
       ATTR: http://schemas.android.com/apk/res/android:versionName='2.7.2'
```

Still:

```diff
  -rw-r--r--  0.0 unx      151 b-       87 defN 1981-01-01 01:01:02 18d19675 assets/flutter_assets/FontManifest.json
- -rw-r--r--  0.0 unx    89548 b-    84523 defN 1981-01-01 01:01:02 d10271c0 assets/flutter_assets/NOTICES.Z
+ -rw-r--r--  0.0 unx    89481 b-    84460 defN 1981-01-01 01:01:02 647b23d3 assets/flutter_assets/NOTICES.Z
  -rw-r--r--  0.0 unx       45 b-       47 defN 1981-01-01 01:01:02 eb8653b5 assets/flutter_assets/NativeAssetsManifest.json
```

There's funnily one MIT license mismatch:

![Image](https://github.com/user-attachments/assets/a59f17ec-10da-4e70-94d1-4e56c4ab82f8)

The difference becomes more clear here:

```diff
-THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR^M
-IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,^M
-FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE^M
-AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER^M
-LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,^M
-OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE^M
-SOFTWARE.^M
+MIT License
+
+Copyright (c) 2021 - 2025 uintdev
+
+Permission is hereby granted, free of charge, to any person obtaining a copy
+of this software and associated documentation files (the "Software"), to deal
+in the Software without restriction, including without limitation the rights
+to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+copies of the Software, and to permit persons to whom the Software is
+furnished to do so, subject to the following conditions:
```

In your APK, that license uses Windows line breaks.

Apart from that, it seems it would be RB.

```yaml
        build:
          - sed -r '/signingConfigs.getByName/d' -i android/app/build.gradle.kts
          - sed -r '/create\("release"\) \{/,/^        \}/d' -i android/app/build.gradle.kts
          - git config --global http.version HTTP/1.1
          - export PUB_CACHE=$(pwd)/.pub-cache
          - flutter/bin/flutter config --no-analytics
          - flutter/bin/flutter pub get
          - flutter/bin/flutter build apk --release --split-per-abi --target-platform android-arm
          - find . -name '*.apk'
          - mv build/app/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk /outputs/unsigned.apk
```

**Comment by uintdev** [comment]
>Where is that? I couldn't find it in the Readme.

This was at the end of running the setup script. The line can be found [here].(https://codeberg.org/IzzyOnDroid/rbuilder_setup/src/commit/845cba84ecef175c6cff586960296bca2646a9e0/scripts/04_rbhelper.sh#L30)

>Best of course if that sed [wouldn't be needed in the first place](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds/RB-Hints-for-Developers#signing-config) 😉

Updated the configuration with the checks and removed the sed steps.

>And now, to get it RB, let's also include --split-per-abi with the flutter build – as otherwise we get a different versionCode
Ah, yes. The version code thing was brought up on issue #27 for another reason. Sure fun. I had added the flag to the command in the recipe.

>In your APK, that license uses Windows line breaks.

Updated various files, including the LICENSE file to use LF.

Currently, this is building. I'll provide an update alone with the new recipe once this is done.

**Comment by uintdev** [comment]
Updated recipe:
```yaml
---
repository: https://github.com/uintdev/qrserv.git
updates: releases
versions:
  - tag: v2.7.3
    apks:
      - apk_pattern: qrserv-.*-armeabi-v7a\.apk
        apk_url: https://github.com/uintdev/qrserv/releases/download/v2.7.3/qrserv-v2_7_3-armeabi-v7a.apk
        build:
          - git config --global http.version HTTP/1.1
          - export PUB_CACHE=$(pwd)/.pub-cache
          - flutter/bin/flutter config --no-analytics
          - flutter/bin/flutter pub get
          - flutter/bin/flutter build apk --release --split-per-abi --target-platform android-arm
          - find . -name '*.apk'
          - mv build/app/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /home/deck
        build_repo_dir: /home/deck/Development/src/qrserv
        build_timeout:
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages:
            - curl
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: false

```
